services:
  card_management:
    container_name: cardmanagement
    build:
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://cardmanagement_db:5432/card_management'
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mint2024
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      JAVA_OPTS: '-Xmx512m'
    depends_on:
      - cardmanagement_db
  cardmanagement_db:
    image: postgres:16.8
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mint2024
      - POSTGRES_DB=card_management
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge