spring:
  application:
    name: cardManagement
  datasource:
    url: jdbc:postgresql://localhost:5432/card_management
    username: postgres
    password: mint2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: g30S/jenSyYhh16AtzTGynJOI3QmeGK950WzKMY/wzw=
      expiration: 3600000 # 1 h
      refresh-token:
        expiration: 3600000 # 1 h
    card:
      secret-key: T5bLsc/gYtQdyErg8/r4VQ==
      encryption-cipher: "AES"

logging:
  level:
    org.springframework:
      security:
        DEBUG
      web:
        DEBUG